### ISSUE TITLE
Separating selectors and declaration with new lines

### ISSUE THREAD

**Issue by zannain** [jolena53/prj-rev-bwfs-dasmoto#3]
When [selecting multiple CSS elements](https://github.com/jolena53/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts%26Craft/resources/style.css#L1-L2) that have a common style per [Google's HTML/CSS style guide](https://google.github.io/styleguide/htmlcssguide.html#Selector_and_Declaration_Separation) it's recommended that selectors and declarations should be on new lines.

_Before_
```css
h1, h2, p {font-family: Helvetica
}
```

_After_
```css
h1, 
h2, 
p {
    font-family: Helvetica
}
```

In general refering to a style guide is an excellent way to pick up on best practices for a language when writing markups, style and code in general!
